import = [
    "~/.config/alacritty/themes/tokyonight-storm.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
opacity=0.85
blur = true
title = "oswgg"
dynamic_title = false
decorations="Buttonless"

[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Medium"
offset.y=4
size = 11
[colors]
transparent_background_colors = true
[terminal]
osc52 = "CopyPaste"
